// Generated by https://quicktype.io

export interface ICustomer {
  id: number;
  name: string;
  address: string;
  fiscal_id: string;
  zip_code: string;
  email: string;
  phone: string;
  green_point: number;
  surcharge: number;
  created_at: string;
  updated_at: string;
}
