// Generated by https://quicktype.io

export interface ICustomer {
  id: string;
  name: string;
  address: string;
  fiscal_id: string;
  route_id: string;
  zip_code: string;
  email: string;
  phone: string;
  is_green_point: boolean;
  is_surcharge: boolean;
  created_at: string;
  updated_at: string;
  is_deprecated: string;
  town: string; // población
  province: string;
  method_of_payment: string;
}
